### ISSUE TITLE
Does not support openssh key types

### ISSUE THREAD

**Issue by cfurst** [Losant/ssl-validator#10]
pub/private key pairs generated by `ssh-keygen` have the following salutation:
`-----BEGIN OPENSSH PRIVATE KEY-----` and end with `-----END OPENSSH PRIVATE KEY-----`
which is not supported as a key type..
Also the public keys for openssh are tricky because they have hostnames in them and how do you detect that as a part of a string.

**Comment by eeerin** [comment]
@cfurst 

We have publish version 4.0.0, which contains a new option skipFormatValidation. This will allow you to skip our key type validation.
