### ISSUE TITLE
Does not work with Angular 11

### ISSUE THREAD

**Issue by gauravupadhyaya** [Losant/ssl-validator#14]
Error: ./node_modules/pem/lib/openssl.js
Module not found: Error: Can't resolve 'child_process' in 'C:\....\node_modules\pem\lib'

Error: ./node_modules/pem/lib/helper.js
Module not found: Error: Can't resolve 'crypto' in 'C:\....\node_modules\pem\lib'

Error: ./node_modules/pem/lib/openssl.js
Module not found: Error: Can't resolve 'crypto' in 'C:\....\node_modules\pem\lib'

Error: ./node_modules/isexe/mode.js
Module not found: Error: Can't resolve 'fs' in 'C:\....\node_modules\isexe'

Error: ./node_modules/isexe/windows.js
Module not found: Error: Can't resolve 'fs' in 'C:\....\node_modules\isexe'

Error: ./node_modules/isexe/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\....\node_modules\isexe'

Error: ./node_modules/pem/lib/helper.js
Module not found: Error: Can't resolve 'fs' in 'C:\....\node_modules\pem\lib'

Error: ./node_modules/pem/lib/openssl.js
Module not found: Error: Can't resolve 'fs' in 'C:\....\node_modules\pem\lib'

Error: ./node_modules/pem/lib/helper.js
Module not found: Error: Can't resolve 'path' in 'C:\....\node_modules\pem\lib'

Error: ./node_modules/pem/lib/openssl.js
Module not found: Error: Can't resolve 'path' in 'C:\....\node_modules\pem\lib'

Error: ./node_modules/pem/node_modules/which/which.js
Module not found: Error: Can't resolve 'path' in 'C:\....\node_modules\pem\node_modules\which'de_modules\which'

**Comment by eeerin** [comment]
this library requires access to openssl executable which is not available in a browser.
