### ISSUE TITLE
Definitions???

### ISSUE THREAD

**Issue by ivose** [Losant/ssl-validator#20]
Maybe you can write better instructions. E.g
await isValidSSL(cert) - how to define cert????
await validateSSLKey(key); - key definition, please.
await validateSSL(cert, {key, domain, bundle}); how to define key, how to devine bundle???? Domain, i understand what is.

**Comment by eeerin** [comment]
Hi @ivose 

In the this test [file](https://github.com/Losant/ssl-validator/blob/master/test/__fixtures__/valid-ssl.js#L1) you can see some of the examples we are using in tests. 

In order to generate your own key, cert, and bundle you will need to use openssl command line.
