### ISSUE TITLE
Support for ENCRYPTED PRIVATE KEY

### ISSUE THREAD

**Issue by marqu3z** [Losant/ssl-validator#28]
https://datatracker.ietf.org/doc/html/rfc7468#section-11

I noticed password-protected private keys are supported, but the label `ENCRYPTED PRIVATE KEY` is identified as invalid header/footer.
Is it possible to support it with a low effort?

**Comment by eeerin** [comment]
@marqu3z I have published 4.0.0 with a new option skipFormatValidation to allow any types of keys or certs to be valid. This way you can create custom validation (if you choose) outside of this library.
