### ISSUE TITLE
it returns false when validate wildcard cert with domain.

### ISSUE THREAD

**Issue by dogenius01** [Losant/ssl-validator#4]
Cert is for *.test.com
and domain is a.test.com.

let cert = `~~~`;
let domain = 'a.test.com';

let result = await sslValidator.isValidSSL(cert, {domain: domain, skipDateValidation: false});

result is false.

**Comment by dogenius01** [comment]
3 depth domain must have more than 2 character.

**Comment by dogenius01** [comment]
how about "m.xxx.com" ??
It should work, right?

**Comment by dogenius01** [comment]
Also, "test.test.xxx.com" always return false.

**Comment by spacetc62** [comment]
Thanks for the issue report (and sorry about our delay in fixing it - somehow missed the notifications). The issue is fixed in [v1.0.6](https://github.com/Losant/ssl-validator/blob/master/CHANGELOG.md#106---2020-02-25)
