### ISSUE TITLE
How to import sslValidator?

### ISSUE THREAD

**Issue by didemkaraaslan** [Losant/ssl-validator#5]
Hi, the question might be silly but how do I access sslValidator?

Is it like import sslValidator from "ssl-validator" or const sslValidator = require("ssl-validator") ??

**Comment by dogenius01** [comment]
```
var sslValidator = require("ssl-validator")
```

Try "https://npm.runkit.com/ssl-validator".

**Comment by spacetc62** [comment]
We have updated the [README](https://github.com/Losant/ssl-validator#validate-ssl) to make it more obvious how to require and use the module. Hope that helps!
